/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2agencia;
import clases.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;
/**
 *
 * @author Juan RigobertoZuñiga
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public static boolean admin1;
    public Clientes(boolean admin) {
        initComponents();
        this.admin1=admin; 
    }
    public Clientes(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Clientes : ");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jScrollPane3.setViewportView(jList3);

        jLabel1.setText("Todos");

        jLabel3.setText("Clientes por Monto");

        jLabel4.setText("Clientes por Frecuencia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 379, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4))
                                    .addComponent(jButton1))))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio in=new Inicio(Login.admin);
        in.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ncliente nuevo=new Ncliente();
        nuevo.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //
        Nodo aux = modulocarga.clientela.inicio;//devuelve el nodo de la lista
        cliente ref;//instancia un objeto para cstear
        String vec[]=new String[modulocarga.clientela.getSize()];
        String platino[]=new String[modulocarga.clientela.getSize()];
        String premiun[]=new String[modulocarga.clientela.getSize()];
        String basico[]=new String[modulocarga.clientela.getSize()];
        String anual[]=new String[modulocarga.clientela.getSize()];
        String mensual[]=new String[modulocarga.clientela.getSize()];
        String regular[]=new String[modulocarga.clientela.getSize()];
        String frecuente[]=new String[modulocarga.clientela.getSize()];
        //aca se llena el vector con espacios vacios
       /* for(int j=0;j<vec.length;j++){            
            platino[j]="";
            premiun[j]="";
            basico[j]="";
            anual[j]="";
            mensual[j]="";
            regular[j]="";
            frecuente[j]="";
        }*/
        //System.out.println(vec.length);
        int i=0,p=0,q=0,r=0;
        int an=0,me=0,re=0,fre=0;
        //while para entrar a cada objeto guardado en la lista
        while (aux!=null){
            ref = (cliente) aux.dato;//devuelve un objeto de casteo
            String cof=ref.nombre+" "+ref.apellido+" "+ref.tarjeta+" "+ref.fechan+" "+ref.telefono+" "+ref.celular+" "+ref.direccionh+" "+ref.frecuencia;
            String loc =ref.codigo+"-----"+ref.nombre+"-----"+ref.apellido+"-----"+ref.tarjeta+"-----"+ref.fechan+"-----"+ref.telefono+"-----"+ref.celular+"-----"+ref.direccionh+"-----"+ref.frecuencia;
            //guardar lo de loc en un vector
            //System.out.println(i);
            //agrega todos los clientes a la lista general
            vec[i]=loc;
            //agrega los clientes a diferentes vectores segun su clasificacion de motno
            switch(ref.getFrecuencia()){
                case "Premiun":
                    premiun[p]=cof;
                    p++;
                case "premiun":
                    premiun[p]=cof;
                    p++;
                    
                case "Platino":
                    platino[q]=cof;
                    q++;
                case "platino":
                    premiun[q]=cof;
                    q++;
                      
                case "Basico":
                    basico[r]=cof;
                    r++;
                case "basico":
                    basico[r]=cof;
                    q++;
                      
            }
            ///aca agraga los clientes por clasificacion de frecuencia
            switch(ref.getMonto()){
                case "Anual":
                    anual[an]=cof;
                    an++;
                case "anual":
                    anual[an]=cof;
                    an++;
                    
                case "Mensual":
                    mensual[me]=cof;
                    me++;
                case "mensual":
                    mensual[me]=cof;
                    me++;
                     
                case "Regular":
                    regular[re]=cof;
                    re++;
                case "regular":
                    regular[re]=cof;
                    re++;
                    
                case "Frecuente":
                    frecuente[fre]=cof;
                    fre++;
                case "frecuente":
                    frecuente[fre]=cof;
                    fre++;
                    
            }
            //dfsdffdsf
            aux = aux.siguiente;//pasa al siguiente nodo
            i++;
            }
       /* for(int j=1;j<vec.length;j++){            
            System.out.println(vec[j]);
            System.out.println("");
            System.out.println(premiun[j]);
            System.out.println("");
            System.out.println(platino[j]);
            System.out.println("");
            System.out.println(basico[j]);
            System.out.println("");
            System.out.println(anual[j]);
            System.out.println("");
            System.out.println(mensual[j]);
            System.out.println("");
            System.out.println(regular[j]);
            System.out.println("");
            System.out.println(frecuente[j]);
        }
        */
        DefaultListModel modelo = new DefaultListModel();
        for(int j=1;j<vec.length;j++){            
            modelo.addElement(vec[j]);
        }
        jList1.setModel(modelo);
        DefaultListModel modelo1 = new DefaultListModel();
        for(int j=1;j<vec.length;j++){            
            modelo1.addElement(platino[j]);
        }
        for(int j=1;j<vec.length;j++){            
            modelo1.addElement(premiun[j]);
        }
        for(int j=1;j<vec.length;j++){            
            modelo1.addElement(basico[j]);
        }
        jList2.setModel(modelo1);
        
        DefaultListModel modelo2 = new DefaultListModel();
        for(int j=1;j<vec.length;j++){            
            modelo2.addElement(anual[j]);
        }
        for(int j=1;j<vec.length;j++){            
            modelo2.addElement(mensual[j]);
        }
        for(int j=1;j<vec.length;j++){            
            modelo2.addElement(regular[j]);
        }
        for(int j=1;j<vec.length;j++){            
            modelo2.addElement(frecuente[j]);
        }
        jList3.setModel(modelo2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EliminarC eliminar=new EliminarC();
        eliminar.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    //javax.swing.JList lista;
}

