/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2agencia;

import clases.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan RigobertoZuñiga
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static boolean admin=false;
    public static int cont=0;
    public Login() {
        initComponents();
        jPasswordField1.setVisible(false);
        jButton3.setVisible(false);
        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Administrador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese Contrase;a");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel1.setVisible(true);
        jPasswordField1.setVisible(true);
        jButton3.setVisible(true);
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jPasswordField1.getText().equals(Proyecto2Agencia.contra)){
            cont++;
            admin=true;
            Inicio init=new Inicio(admin);
            init.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cont++;
        Inicio init=new Inicio(admin);
            init.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (cont>1){
            String cliente="‪C:\\Users\\Juan RigobertoZuñiga\\Desktop\\documentosdeprueba\\05 Clientes.csv";
            String paquete="C:\\Users\\Juan RigobertoZuñiga\\Desktop\\documentosdeprueba\\08 Paquetes.csv";
            eliminarFichero(cliente);
            eliminarFichero(paquete);
            guardardatos(); 
        }
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
public void eliminarFichero(String archivo) {
        try {
            File fichero = new File(archivo);
            if (fichero.delete()) {
                JOptionPane.showMessageDialog(null, "eliminado con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "no eliminado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
public void guardarclientes(String vector[]){
        //procedimiento para guardar en archivo txt
         File Ffichero = new File("‪C:\\Users\\Juan RigobertoZuñiga\\Desktop\\documentosdeprueba\\05 Clientes.csv");
        try {
            FileWriter fw = new FileWriter(Ffichero, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            for (int i = 0; i <vector.length; i++) {
            pw.println(vector[i]);
            }
            pw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
public void guardarpaquetes(String vector[]){
        //procedimiento para guardar en archivo txt
         File Ffichero = new File("‪C:\\Users\\Juan RigobertoZuñiga\\Desktop\\documentosdeprueba\\08 Paquetes.csv");
        try {
            FileWriter fw = new FileWriter(Ffichero, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            for (int i = 0; i <vector.length; i++) {
            pw.println(vector[i]);
            }
            pw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
    public void guardardatos(){
        int i=0;
        Nodo aux = modulocarga.clientela.inicio;//devuelve el nodo de la lista
        cliente ref;
        String vec[]=new String[modulocarga.clientela.getSize()];
        while (aux!=null){
            ref = (cliente) aux.dato;//devuelve un objeto de casteo
            String loc =ref.codigo+","+ref.nombre+","+ref.apellido+","+ref.tarjeta+","+ref.fechan+","+ref.telefono+","+ref.celular+","+ref.direccionh+","+ref.frecuencia;
            vec[i]=loc;
            aux = aux.siguiente;//pasa al siguiente nodo
            i++;
            }
        guardarclientes(vec);
        //guarda datos de aerolineas y buses
        i=0;
        Nodo aux1 = modulocarga.aerobuses.inicio;//devuelve el nodo de la lista
        aerolineaybus ref1;
        String aero[]=new String[modulocarga.clientela.getSize()];
        while (aux1!=null){
            ref1 = (aerolineaybus) aux1.dato;//devuelve un objeto de casteo
            String loc =ref1.codigo+","+ref1.horasal+","+ref1.horallega+","+ref1.capacidad+"-----"+ref1.destino;
            aero[i]=loc;
            aux1 = aux1.siguiente;//pasa al siguiente nodo
            i++;
            }
        //guarda datos de paquetes
        i=0;
        Nodo aux2 = modulocarga.paquetes.inicio;//devuelve el nodo de la lista
        paquete ref2;
        String paque[]=new String[modulocarga.paquetes.getSize()];
        while (aux2!=null){
            ref2 = (paquete) aux2.dato;//devuelve un objeto de casteo
            String loc =ref2.codigo+","+ref2.tipo+","+ref2.clasificacion+","+ref2.cantidad+","+ref2.transporte+","+ref2.hospedage+","+ref2.codcreucero+","+ref2.codrenta+","+ref2.codestino+","+ref2.codlugar+","+ref2.costo;
            paque[i]=loc;
            aux2 = aux2.siguiente;//pasa al siguiente nodo
            i++;
            }
        guardarpaquetes(paque);
    }
}
